---
- name: Create openvpn config file
  template:
    src: server.conf.j2
    dest: "{{ openvpn_base_dir }}/{{ openvpn_config_file }}.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart openvpn

- name: Create client config directory
  file:
    state: directory
    path: "{{ openvpn_base_dir }}/{{ openvpn_client_config_dir }}"
    owner: root
    group: root
    mode: 0755
  when: openvpn_client_config

- name: Setup openvpn service
  service:
    name: "{{ openvpn_service_name }}"
    enabled: true
    state: started
