# Defaults for the role operation

# Clients
clients: 
  - alex
  - phone
  - r

openvpn_fetch_client_configs: true
openvpn_fetch_client_configs_dir: /tmp/ansible
openvpn_fetch_client_configs_suffix: ""


# Directories
openvpn_base_dir: /etc/openvpn/server
openvpn_key_dir: /etc/openvpn/keys
openvpn_ovpn_dir: "{{ openvpn_base_dir }}"

# Firewall
firewalld_default_interface_zone: public
manage_firewall_rules: true
openvpn_firewall: auto
openvpn_masquerade_not_snat: false

# tasks
install_openvpn: no
install_server_keys: no
configure_firewall: no
configure_selinux: yes
generate_client_configs: yes
configure_server: yes